const mongoose = require("mongoose");
const db = require("../models");


mongoose.connect(
    process.env.MONGODB_URI ||
    "mongodb://localhost/app_db"
);

const contactSeed = [
    { "firstName": "Josiah", "lastName": "Gilchrest", "company": "Bluezoom", "streetAddress": "4345 Talmadge Center", "city": "San Diego", "state": "California", "zip": "92121", "country": "USA", "email": "jgilchrest0@miibeian.gov.cn", "phone": "760-876-2447", "interest": "atlanta united" },
    { "firstName": "Beaufort", "lastName": "Berr", "company": "Yotz", "streetAddress": "59 Eastlawn Street", "city": "Cleveland", "state": "Ohio", "zip": "44185", "country": "USA", "email": "bberr1@deliciousdays.com", "phone": "216-374-0661", "interest": "atlanta united" },
    { "firstName": "Nananne", "lastName": "Ruslen", "company": "Tazz", "streetAddress": "1 Summerview Center", "city": "Huntington", "state": "West Virginia", "zip": "25721", "country": "USA", "email": "nruslen2@msu.edu", "phone": "304-702-3640", "interest": "atlanta united" },
    { "firstName": "Beniamino", "lastName": "Whear", "company": "Realfire", "streetAddress": "46 Fisk Trail", "city": "South Bend", "state": "Indiana", "zip": "46634", "country": "USA", "email": "bwhear3@statcounter.com", "phone": "574-542-9507", "interest": "atlanta united" },
    { "firstName": "Tris", "lastName": "Davydkov", "company": "Meevee", "streetAddress": "7806 Express Center", "city": "Oklahoma city", "state": "Oklahoma", "zip": "73109", "country": "USA", "email": "tdavydkov4@geocities.com", "phone": "405-957-8696", "interest": "atlanta united" },
    { "firstName": "Toby", "lastName": "Lawerence", "company": "Thoughtsphere", "streetAddress": "2922 Fordem Crossing", "city": "Brooklyn", "state": "New York", "zip": "11241", "country": "USA", "email": "tlawerence5@hostgator.com", "phone": "347-253-4035", "interest": "atlanta united" },
    { "firstName": "Rafael", "lastName": "Aslam", "company": "Browsetype", "streetAddress": "44 Gina Terrace", "city": "Springfield", "state": "Illinois", "zip": "62723", "country": "USA", "email": "raslam6@apache.org", "phone": "217-480-7134", "interest": "atlanta united" },
    { "firstName": "Bobette", "lastName": "Robez", "company": "Thoughtmix", "streetAddress": "94436 Bultman Circle", "city": "Omaha", "state": "Nebraska", "zip": "68134", "country": "USA", "email": "brobez7@blog.com", "phone": "712-736-4818", "interest": "atlanta united" },
    { "firstName": "Corilla", "lastName": "Delucia", "company": "Blogtags", "streetAddress": "917 Jay Drive", "city": "Topeka", "state": "Kansas", "zip": "66629", "country": "USA", "email": "cdelucia8@youtu.be", "phone": "785-403-5064", "interest": "atlanta united" },
    { "firstName": "Rocky", "lastName": "Checchi", "company": "Reallinks", "streetAddress": "54833 Sommers Drive", "city": "Burbank", "state": "California", "zip": "91505", "country": "USA", "email": "rchecchi9@hhs.gov", "phone": "323-957-7828", "interest": "atlanta united" },
    { "firstName": "Robb", "lastName": "Thay", "company": "Oyoba", "streetAddress": "470 Caliangt Junction", "city": "Kansas city", "state": "Missouri", "zip": "64130", "country": "USA", "email": "rthaya@jalbum.net", "phone": "816-934-1013", "interest": "atlanta united" },
    { "firstName": "Adel", "lastName": "Spens", "company": "Fivespan", "streetAddress": "11 Loftsgordon Place", "city": "Tulsa", "state": "Oklahoma", "zip": "74133", "country": "USA", "email": "aspensb@pen.io", "phone": "918-758-1532", "interest": "atlanta united" },
    { "firstName": "Lida", "lastName": "Raselles", "company": "Edgeify", "streetAddress": "0245 Blue Bill Park Trail", "city": "Fort Lauderdale", "state": "Florida", "zip": "33355", "country": "USA", "email": "lrasellesc@unicef.org", "phone": "754-804-2144", "interest": "atlanta united" },
    { "firstName": "Jehanna", "lastName": "Benitez", "company": "Meejo", "streetAddress": "17525 Lukken Court", "city": "Roanoke", "state": "Virginia", "zip": "24020", "country": "USA", "email": "jbenitezd@usgs.gov", "phone": "540-642-9879", "interest": "atlanta united" },
    { "firstName": "Raymund", "lastName": "Harnes", "company": "Flashset", "streetAddress": "56670 Amoth Parkway", "city": "Baton Rouge", "state": "Louisiana", "zip": "70820", "country": "USA", "email": "rharnese@mapy.cz", "phone": "225-868-8998", "interest": "atlanta united" },
    { "firstName": "Reagan", "lastName": "O' Hogan", "company": "Gigaclub", "streetAddress": "7360 Pankratz Road", "city": "New York city", "state": "New York", "zip": "10260", "country": "USA", "email": "rohoganf@over-blog.com", "phone": "212-945-2477", "interest": "atlanta united" },
    { "firstName": "Burke", "lastName": "Ingley", "company": "Lajo", "streetAddress": "99 Kennedy Hill", "city": "Jacksonville", "state": "Florida", "zip": "32259", "country": "USA", "email": "bingleyg@facebook.com", "phone": "904-209-6444", "interest": "atlanta united" },
    { "firstName": "Kurt", "lastName": "McGiffie", "company": "Feedfish", "streetAddress": "7438 Lyons Junction", "city": "Anaheim", "state": "California", "zip": "92825", "country": "USA", "email": "kmcgiffieh@cbc.ca", "phone": "714-567-5070", "interest": "atlanta united" },
    { "firstName": "Juliane", "lastName": "Plumptre", "company": "Voonix", "streetAddress": "89232 East Hill", "city": "Saint Paul", "state": "Minnesota", "zip": "55146", "country": "USA", "email": "jplumptrei@jimdo.com", "phone": "651-161-7301", "interest": "atlanta united" },
    { "firstName": "Winnie", "lastName": "Harrie", "company": "Innojam", "streetAddress": "53202 Loeprich Road", "city": "San Antonio", "state": "Texas", "zip": "78245", "country": "USA", "email": "wharriej@discovery.com", "phone": "210-715-9469", "interest": "atlanta united" },
    { "firstName": "Jeramie", "lastName": "Doldon", "company": "Zoombox", "streetAddress": "1 Lyons Crossing", "city": "Dallas", "state": "Texas", "zip": "75226", "country": "USA", "email": "jdoldonk@forbes.com", "phone": "972-475-9636", "interest": "atlanta united" },
    { "firstName": "Linet", "lastName": "BoHlingolsen", "company": "Flipbug", "streetAddress": "309 Dawn Terrace", "city": "New York city", "state": "New York", "zip": "10292", "country": "USA", "email": "lbohlingolsenl@ask.com", "phone": "212-264-2817", "interest": "atlanta united" },
    { "firstName": "Arman", "lastName": "Tomowicz", "company": "Brightbean", "streetAddress": "957 Chinook Trail", "city": "New Orleans", "state": "Louisiana", "zip": "70183", "country": "USA", "email": "atomowiczm@seesaa.net", "phone": "504-875-2746", "interest": "atlanta united" },
    { "firstName": "Rob", "lastName": "Splevings", "company": "Voomm", "streetAddress": "060 Columbus Trail", "city": "Boca Raton", "state": "Florida", "zip": "33487", "country": "USA", "email": "rsplevingsn@cargocollective.com", "phone": "305-482-8195", "interest": "atlanta united" },
    { "firstName": "Stanfield", "lastName": "Breckin", "company": "Midel", "streetAddress": "0837 Hanover Crossing", "city": "Washington", "state": "District of Columbia", "zip": "20220", "country": "USA", "email": "sbreckino@xing.com", "phone": "202-228-4375", "interest": "atlanta united" },
    { "firstName": "Augustus", "lastName": "Sandwith", "company": "Livepath", "streetAddress": "775 Schmedeman Hill", "city": "Nashville", "state": "Tennessee", "zip": "37240", "country": "USA", "email": "asandwithp@intel.com", "phone": "615-880-9719", "interest": "atlanta united" },
    { "firstName": "Ivie", "lastName": "Hammerberger", "company": "Browsecat", "streetAddress": "3883 Gerald Park", "city": "Boise", "state": "Idaho", "zip": "83732", "country": "USA", "email": "ihammerbergerq@economist.com", "phone": "208-640-8421", "interest": "atlanta united" },
    { "firstName": "Christy", "lastName": "Brellin", "company": "Quatz", "streetAddress": "1 4th Circle", "city": "Naperville", "state": "Illinois", "zip": "60567", "country": "USA", "email": "cbrellinr@harvard.edu", "phone": "630-158-4945", "interest": "atlanta united" },
    { "firstName": "Quill", "lastName": "Connell", "company": "Brainsphere", "streetAddress": "0609 Valley Edge Crossing", "city": "Alexandria", "state": "Virginia", "zip": "22313", "country": "USA", "email": "qconnells@goodreads.com", "phone": "571-482-3915", "interest": "atlanta united" },
    { "firstName": "Etty", "lastName": "Traher", "company": "Voomm", "streetAddress": "99 Parkside Trail", "city": "Orlando", "state": "Florida", "zip": "32891", "country": "USA", "email": "etrahert@mayoclinic.com", "phone": "407-694-5197", "interest": "atlanta united" },
    { "firstName": "Maynord", "lastName": "Brissenden", "company": "Babblestorm", "streetAddress": "9239 Thompson Circle", "city": "Orlando", "state": "Florida", "zip": "32830", "country": "USA", "email": "mbrissendenu@netscape.com", "phone": "407-565-3417", "interest": "atlanta united" },
    { "firstName": "Anetta", "lastName": "Leheude", "company": "Youbridge", "streetAddress": "08 Fisk Street", "city": "Fort Worth", "state": "Texas", "zip": "76129", "country": "USA", "email": "aleheudev@infoseek.co.jp", "phone": "817-156-4509", "interest": "atlanta united" },
    { "firstName": "Daffi", "lastName": "Aizik", "company": "Tazz", "streetAddress": "18 Melody Street", "city": "Tempe", "state": "Arizona", "zip": "85284", "country": "USA", "email": "daizikw@ustream.tv", "phone": "602-976-2849", "interest": "atlanta united" },
    { "firstName": "York", "lastName": "Arkwright", "company": "Camido", "streetAddress": "854 Melvin Park", "city": "Arlington", "state": "Virginia", "zip": "22244", "country": "USA", "email": "yarkwrightx@archive.org", "phone": "571-774-9376", "interest": "atlanta united" },
    { "firstName": "Cassy", "lastName": "Mathen", "company": "Meevee", "streetAddress": "9 Briar Crest Street", "city": "Bradenton", "state": "Florida", "zip": "34210", "country": "USA", "email": "cmatheny@flavors.me", "phone": "727-523-4211", "interest": "atlanta united" },
    { "firstName": "Ad", "lastName": "Di Biasio", "company": "Linkbuzz", "streetAddress": "5 Hallows Court", "city": "Stockton", "state": "California", "zip": "95298", "country": "USA", "email": "adibiasioz@ezinearticles.com", "phone": "209-908-1058", "interest": "atlanta united" },
    { "firstName": "Kizzie", "lastName": "Clutten", "company": "Jaxspan", "streetAddress": "04016 Brown Park", "city": "Salinas", "state": "California", "zip": "93907", "country": "USA", "email": "kclutten10@github.com", "phone": "831-263-1552", "interest": "atlanta united" },
    { "firstName": "Gwenneth", "lastName": "Anthony", "company": "Quimm", "streetAddress": "08 Clarendon Terrace", "city": "Helena", "state": "Montana", "zip": "59623", "country": "USA", "email": "ganthony11@bbb.org", "phone": "406-960-4987", "interest": "atlanta united" },
    { "firstName": "Cherey", "lastName": "Delwater", "company": "Jayo", "streetAddress": "5 Cordelia Hill", "city": "Salt Lake city", "state": "Utah", "zip": "84105", "country": "USA", "email": "cdelwater12@uiuc.edu", "phone": "801-572-9645", "interest": "atlanta united" },
    { "firstName": "Arnie", "lastName": "Cleugher", "company": "Topicware", "streetAddress": "12972 Summer Ridge Road", "city": "Saint Paul", "state": "Minnesota", "zip": "55115", "country": "USA", "email": "acleugher13@ucoz.ru", "phone": "952-530-7680", "interest": "atlanta united" },
    { "firstName": "Ruthanne", "lastName": "Matteacci", "company": "Yamia", "streetAddress": "79687 Little Fleur Trail", "city": "Fresno", "state": "California", "zip": "93750", "country": "USA", "email": "rmatteacci14@earthlink.net", "phone": "559-649-7039", "interest": "atlanta united" },
    { "firstName": "Washington", "lastName": "Gillibrand", "company": "Topicware", "streetAddress": "0977 Katie Court", "city": "Houston", "state": "Texas", "zip": "77206", "country": "USA", "email": "wgillibrand15@printfriendly.com", "phone": "713-982-2220", "interest": "atlanta united" },
    { "firstName": "Osmond", "lastName": "Ryman", "company": "Oyoloo", "streetAddress": "63 Porter Junction", "city": "Baton Rouge", "state": "Louisiana", "zip": "70894", "country": "USA", "email": "oryman16@cyberchimps.com", "phone": "225-476-1878", "interest": "atlanta united" },
    { "firstName": "Madlin", "lastName": "Backson", "company": "Blogspan", "streetAddress": "44 Algoma Hill", "city": "Lincoln", "state": "Nebraska", "zip": "68517", "country": "USA", "email": "mbackson17@un.org", "phone": "402-850-3754", "interest": "atlanta united" },
    { "firstName": "Letisha", "lastName": "Hovee", "company": "Topicblab", "streetAddress": "298 Drewry Terrace", "city": "Pasadena", "state": "Texas", "zip": "77505", "country": "USA", "email": "lhovee18@howstuffworks.com", "phone": "713-746-3036", "interest": "atlanta united" },
    { "firstName": "Aubrey", "lastName": "Huncoot", "company": "Trupe", "streetAddress": "44 Carioca Hill", "city": "Raleigh", "state": "North Carolina", "zip": "27615", "country": "USA", "email": "ahuncoot19@japanpost.jp", "phone": "919-606-7080", "interest": "atlanta united" },
    { "firstName": "Jeremiah", "lastName": "Aleksandrev", "company": "Jabberstorm", "streetAddress": "93415 Colorado Trail", "city": "Phoenix", "state": "Arizona", "zip": "85040", "country": "USA", "email": "jaleksandrev1a@columbia.edu", "phone": "602-704-2490", "interest": "atlanta united" },
    { "firstName": "Leeland", "lastName": "Ancliffe", "company": "Gabspot", "streetAddress": "44 Portage Park", "city": "Athens", "state": "Georgia", "zip": "30610", "country": "USA", "email": "lancliffe1b@admin.ch", "phone": "706-350-0151", "interest": "atlanta united" },
    { "firstName": "Agneta", "lastName": "Stiller", "company": "Einti", "streetAddress": "382 Northport Place", "city": "Whittier", "state": "California", "zip": "90605", "country": "USA", "email": "astiller1c@printfriendly.com", "phone": "626-268-6503", "interest": "atlanta united" },
    { "firstName": "Onfroi", "lastName": "Wakelin", "company": "Oloo", "streetAddress": "7987 Swallow Plaza", "city": "Greenville", "state": "South Carolina", "zip": "29605", "country": "USA", "email": "owakelin1d@tinyurl.com", "phone": "864-541-2728", "interest": "atlanta united" },
    { "firstName": "Jaime", "lastName": "McGaw", "company": "Livefish", "streetAddress": "62732 Clove Alley", "city": "Murfreesboro", "state": "Tennessee", "zip": "37131", "country": "USA", "email": "jmcgaw1e@zdnet.com", "phone": "615-233-1244", "interest": "atlanta united" },
    { "firstName": "Mimi", "lastName": "Kettell", "company": "Twitterworks", "streetAddress": "674 Mariners Cove Lane", "city": "Honolulu", "state": "Hawaii", "zip": "96805", "country": "USA", "email": "mkettell1f@cdbaby.com", "phone": "808-531-4558", "interest": "atlanta united" },
    { "firstName": "Galvan", "lastName": "Martinat", "company": "Browsebug", "streetAddress": "9465 Beilfuss Alley", "city": "Washington", "state": "District of Columbia", "zip": "20016", "country": "USA", "email": "gmartinat1g@samsung.com", "phone": "202-780-2457", "interest": "atlanta united" },
    { "firstName": "Aland", "lastName": "Carslaw", "company": "Thoughtblab", "streetAddress": "23 Delladonna Street", "city": "Appleton", "state": "Wisconsin", "zip": "54915", "country": "USA", "email": "acarslaw1h@shareasale.com", "phone": "920-966-7349", "interest": "atlanta united" },
    { "firstName": "Vilhelmina", "lastName": "Coopman", "company": "Zoonoodle", "streetAddress": "1 Dottie Center", "city": "Little Rock", "state": "Arkansas", "zip": "72204", "country": "USA", "email": "vcoopman1i@timesonline.co.uk", "phone": "501-375-2824", "interest": "atlanta united" },
    { "firstName": "Hedvig", "lastName": "Barrington", "company": "Reallinks", "streetAddress": "035 Grayhawk Center", "city": "Detroit", "state": "Michigan", "zip": "48242", "country": "USA", "email": "hbarrington1j@nps.gov", "phone": "313-655-5252", "interest": "atlanta united" },
    { "firstName": "Hebert", "lastName": "Guiduzzi", "company": "Zava", "streetAddress": "4788 Vera Court", "city": "Fort Lauderdale", "state": "Florida", "zip": "33345", "country": "USA", "email": "hguiduzzi1k@deviantart.com", "phone": "754-987-2072", "interest": "atlanta united" },
    { "firstName": "Pen", "lastName": "Grishakov", "company": "Browsezoom", "streetAddress": "894 Anniversary Park", "city": "Norfolk", "state": "Virginia", "zip": "23504", "country": "USA", "email": "pgrishakov1l@oaic.gov.au", "phone": "757-158-3689", "interest": "atlanta united" },
    { "firstName": "Jeana", "lastName": "Cockney", "company": "Skiba", "streetAddress": "12 Old Shore Pass", "city": "Tempe", "state": "Arizona", "zip": "85284", "country": "USA", "email": "jcockney1m@opera.com", "phone": "602-351-2453", "interest": "atlanta united" },
    { "firstName": "Farlie", "lastName": "Spenclay", "company": "Jabbertype", "streetAddress": "0472 Melvin Terrace", "city": "Lancaster", "state": "California", "zip": "93584", "country": "USA", "email": "fspenclay1n@yelp.com", "phone": "661-257-4465", "interest": "atlanta united" },
    { "firstName": "Carmela", "lastName": "Caldayrou", "company": "Jaxnation", "streetAddress": "177 Grim Circle", "city": "Wilkes Barre", "state": "Pennsylvania", "zip": "18768", "country": "USA", "email": "ccaldayrou1o@biglobe.ne.jp", "phone": "570-622-1769", "interest": "atlanta united" },
    { "firstName": "Jeno", "lastName": "Shallcross", "company": "Thoughtbeat", "streetAddress": "5265 Glendale Drive", "city": "Detroit", "state": "Michigan", "zip": "48267", "country": "USA", "email": "jshallcross1p@domainmarket.com", "phone": "313-324-4999", "interest": "atlanta united" },
    { "firstName": "Brice", "lastName": "Bernuzzi", "company": "Lajo", "streetAddress": "8122 Columbus Park", "city": "Battle Creek", "state": "Michigan", "zip": "49018", "country": "USA", "email": "bbernuzzi1q@home.pl", "phone": "269-325-1605", "interest": "atlanta united" },
    { "firstName": "Ximenez", "lastName": "Kattenhorn", "company": "Layo", "streetAddress": "8 Oak Parkway", "city": "Stockton", "state": "California", "zip": "95219", "country": "USA", "email": "xkattenhorn1r@loc.gov", "phone": "209-455-0102", "interest": "atlanta united" },
    { "firstName": "Idell", "lastName": "Sangster", "company": "Livepath", "streetAddress": "343 Briar Crest Road", "city": "Oklahoma city", "state": "Oklahoma", "zip": "73124", "country": "USA", "email": "isangster1s@yahoo.com", "phone": "405-539-2844", "interest": "atlanta united" },
    { "firstName": "Reeta", "lastName": "Eronie", "company": "Twitterbeat", "streetAddress": "18 Lake View Court", "city": "Richmond", "state": "Virginia", "zip": "23277", "country": "USA", "email": "reronie1t@google.es", "phone": "804-886-7746", "interest": "atlanta united" },
    { "firstName": "Dorri", "lastName": "Meddows", "company": "Flipstorm", "streetAddress": "50079 Toban Circle", "city": "Sarasota", "state": "Florida", "zip": "34238", "country": "USA", "email": "dmeddows1u@howstuffworks.com", "phone": "941-448-9622", "interest": "atlanta united" },
    { "firstName": "Netta", "lastName": "Buntin", "company": "Yotz", "streetAddress": "0 Scoville Pass", "city": "Orlando", "state": "Florida", "zip": "32808", "country": "USA", "email": "nbuntin1v@globo.com", "phone": "321-873-1714", "interest": "atlanta united" },
    { "firstName": "Rosita", "lastName": "Wellington", "company": "Bubbletube", "streetAddress": "69655 Chive Drive", "city": "Albany", "state": "New York", "zip": "12222", "country": "USA", "email": "rwellington1w@twitpic.com", "phone": "518-906-6880", "interest": "atlanta united" },
    { "firstName": "Wakefield", "lastName": "Cranney", "company": "Mycat", "streetAddress": "315 South Lane", "city": "Toledo", "state": "Ohio", "zip": "43610", "country": "USA", "email": "wcranney1x@dot.gov", "phone": "419-153-2902", "interest": "atlanta united" },
    { "firstName": "Eula", "lastName": "Stronack", "company": "Tekfly", "streetAddress": "58 Lakeland Pass", "city": "Kansas city", "state": "Missouri", "zip": "64142", "country": "USA", "email": "estronack1y@joomla.org", "phone": "816-844-5487", "interest": "atlanta united" },
    { "firstName": "Gothart", "lastName": "MacKean", "company": "Meedoo", "streetAddress": "94036 Fremont Street", "city": "Ogden", "state": "Utah", "zip": "84409", "country": "USA", "email": "gmackean1z@shinystat.com", "phone": "801-114-9833", "interest": "atlanta united" },
    { "firstName": "Gris", "lastName": "Birkmyr", "company": "Twimbo", "streetAddress": "90091 Golf View Road", "city": "Houston", "state": "Texas", "zip": "77245", "country": "USA", "email": "gbirkmyr20@nifty.com", "phone": "713-167-4524", "interest": "atlanta united" },
    { "firstName": "Nerte", "lastName": "Gilby", "company": "Twitterworks", "streetAddress": "2645 Harper Park", "city": "Jackson", "state": "Mississippi", "zip": "39236", "country": "USA", "email": "ngilby21@twitpic.com", "phone": "601-226-4540", "interest": "atlanta united" },
    { "firstName": "Jerald", "lastName": "Casiroli", "company": "Skipstorm", "streetAddress": "10 Sunfield Road", "city": "Birmingham", "state": "Alabama", "zip": "35244", "country": "USA", "email": "jcasiroli22@cnn.com", "phone": "205-960-0013", "interest": "atlanta united" },
    { "firstName": "Henderson", "lastName": "Benettelli", "company": "Fiveclub", "streetAddress": "2 Crownhardt Crossing", "city": "Miami", "state": "Florida", "zip": "33142", "country": "USA", "email": "hbenettelli23@businessinsider.com", "phone": "305-631-9438", "interest": "atlanta united" },
    { "firstName": "Bogart", "lastName": "Kordas", "company": "Centizu", "streetAddress": "40874 Dayton Hill", "city": "Arlington", "state": "Virginia", "zip": "22217", "country": "USA", "email": "bkordas24@bloglovin.com", "phone": "571-699-2216", "interest": "atlanta united" },
    { "firstName": "Gerri", "lastName": "Agostini", "company": "Viva", "streetAddress": "27 Heffernan Parkway", "city": "Pittsburgh", "state": "Pennsylvania", "zip": "15261", "country": "USA", "email": "gagostini25@addtoany.com", "phone": "412-161-9521", "interest": "atlanta united" },
    { "firstName": "Rae", "lastName": "Dash", "company": "Zoombeat", "streetAddress": "703 Lotheville Street", "city": "Naperville", "state": "Illinois", "zip": "60567", "country": "USA", "email": "rdash26@ovh.net", "phone": "630-702-6505", "interest": "atlanta united" },
    { "firstName": "Garold", "lastName": "Child", "company": "Thoughtbeat", "streetAddress": "7513 Crest Line Center", "city": "New York city", "state": "New York", "zip": "10170", "country": "USA", "email": "gchild27@aboutads.info", "phone": "646-524-6136", "interest": "atlanta united" },
    { "firstName": "Giana", "lastName": "Brosnan", "company": "Blogpad", "streetAddress": "300 Susan Trail", "city": "Springfield", "state": "Illinois", "zip": "62764", "country": "USA", "email": "gbrosnan28@acquirethisname.com", "phone": "217-387-4915", "interest": "atlanta united" },
    { "firstName": "Jaquith", "lastName": "Coady", "company": "Voomm", "streetAddress": "15386 Acker Plaza", "city": "Fresno", "state": "California", "zip": "93709", "country": "USA", "email": "jcoady29@w3.org", "phone": "559-927-1388", "interest": "atlanta united" },
    { "firstName": "Stacy", "lastName": "Hucke", "company": "Linkbuzz", "streetAddress": "7919 Armistice Lane", "city": "Waterloo", "state": "Iowa", "zip": "50706", "country": "USA", "email": "shucke2a@icq.com", "phone": "319-131-0813", "interest": "atlanta united" },
    { "firstName": "Willabella", "lastName": "Gatheral", "company": "Skimia", "streetAddress": "9353 Schlimgen Street", "city": "Des Moines", "state": "Iowa", "zip": "50305", "country": "USA", "email": "wgatheral2b@about.com", "phone": "515-101-6235", "interest": "atlanta united" },
    { "firstName": "Ellen", "lastName": "Calabry", "company": "Voonix", "streetAddress": "5527 Hermina Alley", "city": "Tallahassee", "state": "Florida", "zip": "32399", "country": "USA", "email": "ecalabry2c@harvard.edu", "phone": "850-994-5355", "interest": "atlanta united" },
    { "firstName": "Rouvin", "lastName": "Stetlye", "company": "Skalith", "streetAddress": "36972 Tennessee Place", "city": "Bellevue", "state": "Washington", "zip": "98008", "country": "USA", "email": "rstetlye2d@ycombinator.com", "phone": "425-330-0211", "interest": "atlanta united" },
    { "firstName": "Gannie", "lastName": "Ivanovic", "company": "Ooba", "streetAddress": "35 Melvin Crossing", "city": "Greensboro", "state": "North Carolina", "zip": "27425", "country": "USA", "email": "givanovic2e@amazon.de", "phone": "336-435-5598", "interest": "atlanta united" },
    { "firstName": "Dania", "lastName": "Clarycott", "company": "Flashdog", "streetAddress": "30 Rockefeller Junction", "city": "Kansas city", "state": "Missouri", "zip": "64114", "country": "USA", "email": "dclarycott2f@webnode.com", "phone": "816-502-7817", "interest": "atlanta united" },
    { "firstName": "Brynna", "lastName": "Learoyd", "company": "Edgepulse", "streetAddress": "07822 Mayer Road", "city": "Fargo", "state": "North Dakota", "zip": "58106", "country": "USA", "email": "blearoyd2g@mapy.cz", "phone": "701-492-8770", "interest": "atlanta united" },
    { "firstName": "Arlina", "lastName": "Iglesia", "company": "Camido", "streetAddress": "46 Novick Drive", "city": "Baton Rouge", "state": "Louisiana", "zip": "70810", "country": "USA", "email": "aiglesia2h@un.org", "phone": "225-561-6370", "interest": "atlanta united" },
    { "firstName": "Mehetabel", "lastName": "Vowells", "company": "Tekfly", "streetAddress": "113 Hanson Trail", "city": "Naples", "state": "Florida", "zip": "34102", "country": "USA", "email": "mvowells2i@yolasite.com", "phone": "239-404-5773", "interest": "atlanta united" },
    { "firstName": "Kathlin", "lastName": "Orteu", "company": "Gigabox", "streetAddress": "014 Glacier Hill Circle", "city": "Jacksonville", "state": "Florida", "zip": "32209", "country": "USA", "email": "korteu2j@goo.ne.jp", "phone": "904-799-4178", "interest": "atlanta united" },
    { "firstName": "Carlyn", "lastName": "Baitman", "company": "Buzzshare", "streetAddress": "0940 Mitchell Place", "city": "San Francisco", "state": "California", "zip": "94147", "country": "USA", "email": "cbaitman2k@wired.com", "phone": "415-357-7705", "interest": "atlanta united" },
    { "firstName": "Omero", "lastName": "Goddard", "company": "Topicstorm", "streetAddress": "361 Arizona Road", "city": "Tampa", "state": "Florida", "zip": "33673", "country": "USA", "email": "ogoddard2l@theglobeandmail.com", "phone": "813-101-2981", "interest": "atlanta united" },
    { "firstName": "Hortensia", "lastName": "Laurie", "company": "Twitterworks", "streetAddress": "16693 Hoffman Street", "city": "Wilkes Barre", "state": "Pennsylvania", "zip": "18768", "country": "USA", "email": "hlaurie2m@miitbeian.gov.cn", "phone": "570-899-3571", "interest": "atlanta united" },
    { "firstName": "Margaux", "lastName": "Furphy", "company": "Mycat", "streetAddress": "1 Hoard Way", "city": "Greensboro", "state": "North Carolina", "zip": "27404", "country": "USA", "email": "mfurphy2n@ucsd.edu", "phone": "336-749-1452", "interest": "atlanta united" },
    { "firstName": "Shirley", "lastName": "Thoumasson", "company": "Dabfeed", "streetAddress": "07 Burning Wood Way", "city": "Boston", "state": "Massachusetts", "zip": "2216", "country": "USA", "email": "sthoumasson2o@opensource.org", "phone": "617-948-4784", "interest": "atlanta united" },
    { "firstName": "Marge", "lastName": "Varrow", "company": "Oodoo", "streetAddress": "4 Caliangt Lane", "city": "Jamaica", "state": "New York", "zip": "11470", "country": "USA", "email": "mvarrow2p@mlb.com", "phone": "718-135-7875", "interest": "atlanta united" },
    { "firstName": "Ole", "lastName": "Northam", "company": "Kaymbo", "streetAddress": "26 Towne Plaza", "city": "Oakland", "state": "California", "zip": "94616", "country": "USA", "email": "onortham2q@vistaprint.com", "phone": "510-888-6553", "interest": "atlanta united" },
    { "firstName": "Irvin", "lastName": "Orrell", "company": "Flashspan", "streetAddress": "5 Carioca Park", "city": "Carlsbad", "state": "California", "zip": "92013", "country": "USA", "email": "iorrell2r@simplemachines.org", "phone": "760-954-8377", "interest": "atlanta united" },

];

db.Contact
    .remove({})
    .then(() => db.Contact.insertMany(contactSeed))
    .then(data => {
        console.log(data.length + " records inserted!");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1);
    });
